# Generated by Django 3.2.16 on 2025-03-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория ДДС',
                'verbose_name_plural': 'Категории ДДС',
            },
        ),
        migrations.CreateModel(
            name='DDSStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус ДДС',
                'verbose_name_plural': 'Статусы ДДС',
            },
        ),
        migrations.CreateModel(
            name='DDSSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ddscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория ДДС',
                'verbose_name_plural': 'Подкатегории ДДС',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DDSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип ДДС',
                'verbose_name_plural': 'Типы ДДС',
            },
        ),
        migrations.CreateModel(
            name='FinancialMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата создания записи. Можно изменить вручную.', verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Количество средств в рублях', max_digits=12, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, help_text='Комментарий к записи', max_length=100, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ddscategory', verbose_name='Категория')),
                ('move_type', models.ForeignKey(help_text='Тип затраты. Списание или Пополнение', on_delete=django.db.models.deletion.PROTECT, to='api.ddstype', verbose_name='Тип')),
                ('status', models.ForeignKey(help_text='Статус траты. Бизнес, Личное, Налог и т.д.', on_delete=django.db.models.deletion.PROTECT, to='api.ddsstatus', verbose_name='Тип')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ddssubcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Записть ДДС',
                'verbose_name_plural': 'Записи ДДС',
                'ordering': ['-date'],
            },
        ),
    ]
