# Generated by Django 3.2.16 on 2025-03-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmove',
            old_name='move_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='financialmove',
            name='status',
            field=models.ForeignKey(help_text='Статус траты. Бизнес, Личное, Налог и т.д.', on_delete=django.db.models.deletion.PROTECT, to='api.ddsstatus', verbose_name='Статус'),
        ),
    ]
